<?xml version="1.0" encoding="utf-8"?><Database Name="PaDb" Class="PaDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\PaDb.mdf;Integrated Security=True" SettingsObjectName="PhoneAnalyzer.Properties.Settings" SettingsPropertyName="PaDbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Worker" Member="Workers">
    <Type Name="Worker">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubdivisionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fio" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Salary" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Worker_Number" Member="Numbers" ThisKey="Id" OtherKey="WorkerId" Type="Number" />
      <Association Name="Subdivision_Worker" Member="Subdivision" ThisKey="SubdivisionId" OtherKey="Id" Type="Subdivision" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Number" Member="Numbers">
    <Type Name="Number">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WorkerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Number_Call" Member="Calls" ThisKey="Id" OtherKey="NumberId" Type="Call" />
      <Association Name="Worker_Number" Member="Worker" ThisKey="WorkerId" OtherKey="Id" Type="Worker" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Subdivision" Member="Subdivisions">
    <Type Name="Subdivision">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DirectorFio" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="Subdivision_Worker" Member="Workers" ThisKey="Id" OtherKey="SubdivisionId" Type="Worker" />
      <Association Name="Subdivision_AtcCall" Member="AtcCalls" ThisKey="Id" OtherKey="SubdivisionId" Type="AtcCall" />
    </Type>
  </Table>
  <Table Name="dbo.Call" Member="Calls">
    <Type Name="Call">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NumberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ToNumber" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Duration" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Association Name="Number_Call" Member="Number" ThisKey="NumberId" OtherKey="Id" Type="Number" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Settings" Member="Settings">
    <Type Name="Setting">
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AtcCall" Member="AtcCalls">
    <Type Name="AtcCall">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubdivisionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ToNumber" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Duration" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Subdivision_AtcCall" Member="Subdivision" ThisKey="SubdivisionId" OtherKey="Id" Type="Subdivision" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CloseSite" Member="CloseSites">
    <Type Name="CloseSite">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>